/**
 * MODULE: app.manifest
 * PURPOSE: Web App Manifest — makes PITCHUP installable to the home screen
 *          (Android Chrome "Install app" + iOS Safari "Add to Home Screen"),
 *          launching standalone (no browser chrome). Served at
 *          /manifest.webmanifest and linked via layout metadata.
 * LAYER: interfaces
 * NOTES:
 *   - theme/background = cream (#f5f0e8) to match the app's top surface so the
 *     status bar + Android launch splash blend seamlessly (no colour band).
 *   - Icons live in public/icons (generated by scripts/gen-pwa-icons.cjs):
 *     192/512 "any" + a 512 "maskable" (ball inside the safe zone).
 */
import type { MetadataRoute } from "next";

export default function manifest(): MetadataRoute.Manifest {
  return {
    name: "PITCHUP",
    short_name: "PITCHUP",
    description: "Pickup football matchmaking",
    start_url: "/",
    scope: "/",
    display: "standalone",
    orientation: "portrait",
    background_color: "#f5f0e8",
    theme_color: "#f5f0e8",
    icons: [
      {
        src: "/icons/icon-192.png",
        sizes: "192x192",
        type: "image/png",
        purpose: "any",
      },
      {
        src: "/icons/icon-512.png",
        sizes: "512x512",
        type: "image/png",
        purpose: "any",
      },
      {
        src: "/icons/icon-maskable-512.png",
        sizes: "512x512",
        type: "image/png",
        purpose: "maskable",
      },
    ],
  };
}
